# Generated by Django 2.1.5 on 2019-01-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter_name', models.CharField(max_length=100)),
                ('commenter_time', models.DateTimeField(verbose_name='Time to leave a message')),
                ('commenter_content', models.CharField(max_length=400)),
            ],
        ),
    ]
